title: GitHub Bootcamp
description: >-
  This is is a sample Jekyll website that is hosted in GitHub Pages.

twitter_username: renevo
github_username: renevanosnabrugge
theme: minima
markdown: kramdown